### PR TITLE
Home Page

### PR DESCRIPTION
**Pull request by sayamkanwar**
Hi,
I have designed the homepage for Fabrik including all the deliverables. Previous PR: https://github.com/Cloud-CV/Fabrik/pull/486.

Demo
new_homepage

Please review @Ram81 @RishabhJain2018 
Thank you! :)

### CODE REVIEW

**Review by Ram81 — CHANGES_REQUESTED** [review]
@sayamkanwar please re-open this PR on dashboard branch as we would want to integrate this with dashboard, signup and login page

**Comment by sayamkanwar** [comment]
Yes, I'll do that.

**Comment by sayamkanwar** [comment]
@Ram81, re-opened the PR on dashboard branch: https://github.com/Cloud-CV/Fabrik/pull/505
Should I close this PR?

**Comment by sayamkanwar** [comment]
Closing this PR as PR re-opened on ``user-dashboard`` branch

**Pull request closed without merging**
