### PR TITLE
Fix #118: Add another VQA Model for Keras

### LINKED ISSUE #118: Add VQA model in model zoo for Keras
Fabrik can build / visualize very complex multi-modal architectures using Keras. One of the popular tasks for which we should add a model in model zoo is VQA. Here are some examples: 

- Keras JSON files that can directly be imported: https://github.com/avisingh599/visual-qa/tree/master/models
- https://github.com/anantzoid/VQA-Keras-Visual-Question-Answering
- https://github.com/iamaaditya/VQA_Demo

### PR DESCRIPTION
**Pull request by galiaxy**
I added [this](https://github.com/anantzoid/VQA-Keras-Visual-Question-Answering) VQA model for issue #118. 
This is a screenshot of it:
screenshot from 2018-01-04 17-35-13
It looks similar to the existing VQA model, but different.

### CODE REVIEW

**Comment by utsavgarg** [comment]
@galiaxy It's a nice effort, a few changes:
* Please also add the link to visualize this model in the tested models' list. (Check discussion in https://github.com/Cloud-CV/Fabrik/pull/235 for details)
* Also this seems to be missing the CNN portion which is shown in the overview diagram in the repo you linked.

**Comment by galiaxy** [comment]
- Okay, I will
- I'm sorry I don't understand. Could you explain more please?

Thanks :)

**Comment by galiaxy** [comment]
Alright, I've added a link to visualize this model, and I don't think there's any convolutional layer (CNN, if that's what you meant) in the model. Yes, there's a script to import convolutional layers in the model, but it's not used at all.

**Comment by utsavgarg** [comment]
LGTM :)

**Pull request merged**
