### PR TITLE
Update README - sudo -u -> sudo -i -u

### PR DESCRIPTION
**Pull request by trexdinosaur**
Proper usage from sudoing into another user should be -i . Just a -u  throws an error.

### CODE REVIEW

**Comment by PalashTanejaPro** [comment]
@trexdinosaur hey, have you tried replicating this issue though. I have installed 3 times with just -u and have faced no problems whatsoever.

**Comment by trexdinosaur** [comment]
Which OS are you on?
________________________________

**Comment by trexdinosaur** [comment]
Oh I see, you've chosen to directly open a psql with just that one command. That works, I thought the intent was to open another shell.

**Comment by trexdinosaur** [comment]
However, if psql is already open, why do we have to run psql -c for each command? I'll try to redo it on my side, and I'll reopen the PR if need be. Thanks.

**Comment by trexdinosaur** [comment]
ok I tested it some more. @PalashTanejaPro, your method works, but it maybe better to use normal SQL statements with a semicolon at the end. 

Two Reasons:
1) Running these SQL commands as a normal command, rather than invoking another psql shell, makes the commands more verbose and shows the errors. 
2) If someone is running on a postgresql server where postgres is not the user they are working with, they would have to change postgres with every single line of command, while if they were just pure commands, only one change would be needed to run it as a different user.

**Comment by PalashTanejaPro** [comment]
@trexdinosaur I think that there is clearly some difference in the outputs that we are getting. Why don't you watch the [installation guide](https://www.youtube.com/watch?v=zPgoben9D1w) that I made, so that you can understand my perspective better?

**Comment by trexdinosaur** [comment]
@PalashTanejaPro, I think I may be unclear what I am referring to, let me update the PR with what I mean. 
@5:37, you enter all those commands into an instance of psql, but because you are spawning another instance of it, within psql, there are no outputs. After each statement, there should be messages like ALTER table or failed, but because of the spawning, it's not happening.  I'll update the PR in a bit to what I am referring to.

**Comment by trexdinosaur** [comment]
Updated!

**Comment by JPJPJPOPOP** [comment]
@trexdinosaur I told PalashTanejaPro about this same issue, i.e. I needed to run sudo -i -u too. I really don't know why, as it never gave me an error, but if I don't, I don't get any outputs from psql.

The image below shows what I think should be the correct thing:

**Comment by trexdinosaur** [comment]
@JPJPJPOPOP , you're doing something a bit different. @PalashTanejaPro originally wanted to spawn psql's within psql's. That was fine, just inefficient. @JPJPJPOPOP the reason you had to use -i is because you forgot to invoke a psql shell, which then requires you to use sudo -i to make to it interactive. If you click see file changed, I have added the method I think is best for the installation.

**Comment by PalashTanejaPro** [comment]
@trexdinosaur Just to clear it up a little bit, it wasn't me who added those commands. They were added by the original creators of the project.

**Comment by utsavgarg** [comment]
LGTM :+1:  Thanks, @trexdinosaur :).

**Pull request merged**
