### PR TITLE
Make A Sign In Page At /accounts/login

### PR DESCRIPTION
**Pull request by coler706**
Adds/Styles the /accounts/login page integrated into the current django allauth setup.

### CODE REVIEW

**Comment by Ram81** [comment]
@coler706  can you share a screen shot of the login page designed, so that we can iterate over the design.

**Comment by coler706** [comment]
[
screenshot from 2018-10-28 14-21-21
](url)

the 0.0.0.0:8000 url will be replaced by the actual url when deployed (I ran the website at 0.0.0.0:8000)

**Comment by Ram81** [comment]
@coler706 can you design some more mock-ups for login page, this design doesn't match with Fabrik theme. For reference have a look at evalai.cloudcv.org.

**Comment by coler706** [comment]
Hmm that login page seems to be a different style than the rest of fabrik but ok.

**Comment by Ram81** [comment]
@coler706 are you still working on this?

**Comment by Ram81** [comment]
Closing this, as login panel was added in #424 and the student has abandoned the task.

**Pull request closed without merging**
