### PR TITLE
Add UNET to The Model Zoo

### PR DESCRIPTION
**Pull request by galiaxy**
I added [UNET](https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model) to the Model Zoo, this is a screenshot:
unet model
I've also made sure that I can export it successfully.

### CODE REVIEW

**Comment by gautamjajoo** [comment]
@galiaxy I think so Utsav sir told that they are only adding popular models. WHile you can add to tested models.md .

**Comment by galiaxy** [comment]
@gautamjajoo Right, although I  think UNet is a pretty popular model, except this UNet I added here, is a modification - so yes, I've been thinking about that too. Well, should I try another model then?

**Comment by gautamjajoo** [comment]
@galiaxy So you can try Neuraltalk2

**Comment by galiaxy** [comment]
@gautamjajoo True - but it uses Torch so I should convert it first

**Comment by virajprabhu** [comment]
LGTM, thanks @galiaxy!

**Pull request merged**
