### PR TITLE
added cifar10_cnn model from caffe to zoo

### PR DESCRIPTION
**Pull request by nchhaj189**

### CODE REVIEW

**Comment by utsavgarg** [comment]
Hi, the export to Keras is not working, in the future check that export to at least the framework from which you are importing works. Also, add the model to `tested_models` list in the tutorials folder and add a link to the source from where you got this network.

**Comment by virajprabhu** [comment]
Thanks @nchhaj189. Can you modify the PR name to the right model?

**Comment by virajprabhu** [comment]
The correct title should also be displayed in the model zoo dashboard, and in the title pane on the canvas.

**Comment by virajprabhu** [comment]
image

**Comment by utsavgarg** [comment]
LGTM :)

**Pull request merged**
