### PR TITLE
Add installation of webpack

### PR DESCRIPTION
**Pull request by trexdinosaur**

### CODE REVIEW

**Comment by PalashTanejaPro** [comment]
@trexdinosaur @utsavgarg Can I add my video installation guide to the Readme. 
It has every single instruction from cd to webpack installation. 
It would be much less intimidating for a new user.
If you guys want then you can make an official CloudCV channel and I will give the footage to you.

**Comment by trexdinosaur** [comment]
@PalashTanejaPro I think you sent it in the Gitter channel a little while and it looked good to me!

**Comment by trexdinosaur** [comment]
@PalashTanejaPro if you want to add it to this PR, you can submit a PR to my master branch

**Comment by utsavgarg** [comment]
@PalashTanejaPro You can add a link to it under the documentations heading in the Readme

**Pull request merged**
