### PR TITLE
Fix #184: Export fails after layer is added

### LINKED ISSUE #184: Export fails after layer is added
Export fails if a new layer is added to a model that has been loaded from the Fabrik model zoo.
Steps to recreate:
-  Load YoloNet from the Fabrik model zoo
- Add a Softmax loss layer
- Click on export to Caffe

### PR DESCRIPTION
**Pull request by NSDCars5**
The endPoint property seems to be causing problems, as this information is Fabrik-specific and not related to Caffe.

### CODE REVIEW

**Comment by utsavgarg** [comment]
@NSDCars5 This doesn't seem to fix the bug, I am still getting the same error. Were you able to reproduce the error by following the steps mentioned in the issue?

**Comment by NSDCars5** [comment]
@utsavgarg Yes, I was, and making this change fixed it on my end - I was able to export a prototxt and re-import it into Fabrik.

**Comment by utsavgarg** [comment]
@NSDCars5 After this change, it is indeed exporting a model, but the exported model does not contain the added layers.

**Comment by NSDCars5** [comment]
@utsavgarg This is what I get: https://www.youtube.com/watch?v=Dbv4is0EFGM

Does the position of the layers have to be preserved? Other than that it seems to work fine for me, the new layers are shown once I import it.

**Comment by utsavgarg** [comment]
@NSDCars5 It works if you drag and drop a layer but doesn't work if you click and add a layer. You can see the video below to get a better understanding of what I mean
https://drive.google.com/open?id=124G_gKPe0CO3K4T9X3wcBkjkbQTqAv3j

**Comment by NSDCars5** [comment]
@utsavgarg Hey, I think this is a problem with the handleClick function not properly joining a layer added manually. Working on a fix.

**Comment by NSDCars5** [comment]
@utsavgarg Should work fine now.

**Comment by utsavgarg** [comment]
LGTM :)

**Pull request merged**
