### PR TITLE
Ui changes - allows user to click on the row, and not just the arrow

### PR DESCRIPTION
**Pull request by trexdinosaur**
Ui changes - allows user to click on the row, and not just the arrow

Also, can I change up how the pane works, and have the data be served from django and then rendered in a React component? I think it is a bit redundant right now. 

Thanks.

### CODE REVIEW

**Comment by JPJPJPOPOP** [comment]
@trexdinosaur Could you also try fixing a bug with the arrows? Currently if you select on an arrow and activate a dropdown, but then select another row's dropdown, the dropdown reverts, but the arrow still points down.

screen shot 2017-12-11 at 11 51 59 pm

**Comment by utsavgarg** [comment]
Also, the colour of the menu items should not change.
image

And any changes to make the code more efficient are welcome, so go ahead :+1:

**Comment by trexdinosaur** [comment]
PR has been updated @utsavgarg!

**Comment by utsavgarg** [comment]
@trexdinosaur when you click in between the name and the arrow, the arrow symbol changes but the menu is not expanded. If we are changing it, we should change it so that a click anywhere on the row should expand the menu.

image

**Comment by trexdinosaur** [comment]
@utsavgarg updated!

**Pull request merged**
