### PR TITLE
Addition of Inception v4 to the Zoo

### PR DESCRIPTION
**Pull request by Fenil3510**
This PR is for the addition of Inception_v4 model to the Zoo.
It is fundamentally different from v3 , as it has Resnets combined with Inception architecture.
As described in the paper
https://arxiv.org/abs/1602.07261
Please review

### CODE REVIEW

**Comment by Ram81** [comment]
@Fenil3510 can you add it to tested_models.md too

**Comment by thatbrguy** [comment]
@Fenil3510 The tab and new-line characters in your uploaded json file are missing. Please rectify that

**Comment by Fenil3510** [comment]
@thatbrguy I have formatted the json. Please review.

@Ram81 there seems to be an issue importing the json on the fabrik cloud webpage. I tried importing/exporting on my local machine with keras/tf and It works fine.So , I cant really generate a URL for the model so that it could be put in tested_models.md.
Any suggestions?

**Comment by Ram81** [comment]
@Fenil3510 sorry for missing this

**Pull request merged**
