### PR TITLE
Fix #117: Add a title pane

### LINKED ISSUE #117: Add a title pane
We should add a title pane with the model name – this should be an editable field which:
* defaults to untitled if the user is building a model from scratch
* takes the name of whatever the model file is called if loading from zoo / importing from any framework
* Should go into DB – when a shared link is opened, the same name should show up.

### PR DESCRIPTION
**Pull request by NSDCars5**
The default name for a net is Untitled. When a net is loaded from the model zoo, its name is loaded into the textbox provided, which can be changed, and the changed name will be reflected in the exported file.

### CODE REVIEW

**Comment by utsavgarg** [comment]
Nice work :+1: Can you change the position of the net name field to be on the canvas on top of the network.

**Comment by NSDCars5** [comment]
@utsavgarg Made the required changes.

**Comment by utsavgarg** [comment]
@NSDCars5 please centre it on the canvas and add a faint underline so it's clearer that it's editable

**Comment by NSDCars5** [comment]
Not sure why the Travis build is failing, I only changed the UI...

**Comment by utsavgarg** [comment]
Please merge with master, there was a small bug which was recently fixed which might have caused the build to fail.

**Pull request merged**
