### PR TITLE
Fix #105: Added CaffeNet model

### LINKED ISSUE #105: Add models to the Fabrik Model Zoo
We want to make the Fabrik ModelZoo a rich collection of models from all streams of deep learning research (vision, speech, text) and want to add models from both frameworks that are currently well supported by this project (Caffe and Keras).

For people looking to get started with contributing to this project, this is a very good starting point. To add a model to the model zoo, please do the following:
- Add the model prototxt/json to the `example/<framwork>` folder depending on the model being from caffe or keras
- Add the entry to the models drop-down list on the front-end 
- Test if loading the model and exporting it to both or at least one framework is working fine

### PR DESCRIPTION
**Pull request by suraj44**
I've added the BVLC CaffeNet Model
This is the link to the model:
https://github.com/BVLC/caffe/tree/master/models/bvlc_reference_caffenet

### CODE REVIEW

**Comment by virajprabhu** [comment]
@suraj44 Thanks! Please update the description of the PR with more details, for eg. a (stable) link to the CaffeNet model you're adding.

**Comment by suraj44** [comment]
Is the description fine now?

**Comment by virajprabhu** [comment]
Yup, thanks! Please address review comments and update your PR as well.

**Comment by suraj44** [comment]
Can the PR be merged now?

**Comment by prakharchoudhary** [comment]
@suraj44 Please have a look at PR #114. The conversation thread will help you understand the status of your PR.

**Comment by dexter1691** [comment]
@suraj44 : Sorry about this, but as @prakharchoudhary mentioned, CaffeNet model is very similar to AlexNet and therefore having it in ModelZoo is redundant. 

Usually it's good practice to search in closed issues / PRs to see if people have already done whatever you are working on. Also, in future, if you are adding a new model in the model zoo then, commenting on the issue to let everyone know might smooth this process. 

There are other issues open too for adding new models into the model zoo. I encourage you to try those out. They might be slightly more fun / challenging! ;) 

I will close this PR now.

**Comment by virajprabhu** [comment]
@suraj44 Wow, I somehow missed that it's a near-identical similar model and assumed it was in response to an open issue. Sorry about that. Do take a look at other issue threads for models we would like to have.

**Pull request closed without merging**
