### PR TITLE
Split requirements into production and dev

### PR DESCRIPTION
**Pull request by utsavgarg**
- Adds a new script to install caffe and tensorflow if required #51 
- Splits the requirements depending on use case

### CODE REVIEW

**Comment by deshraj** [comment]
Can we have a common.txt which will contain the requirements that are shared across dev and production environment ?

**Comment by utsavgarg** [comment]
@deshraj I can change the prod one to common, we currently don't have any dependencies which are required in prod and not in dev

**Comment by deshraj** [comment]
Sounds good.

**Comment by utsavgarg** [comment]
@deshraj you can now merge the changes

**Pull request merged**
