### PR TITLE
Add SimpleNet model to FabrikZoo( #105)

### PR DESCRIPTION
**Pull request by Shivanshmundra**
Fix: #105 Added SimpleNet 101 model(close to state of art model in classification in terms of less parameters).

### CODE REVIEW

**Comment by Shivanshmundra** [comment]
Any suggestions for improvisations are welcome.

**Comment by thatbrguy** [comment]
@Shivanshmundra Add your model's shareable link and source to this [file](https://github.com/Cloud-CV/Fabrik/blob/master/tutorials/tested_models.md), and commit the changes to this PR.

**Comment by gautamjajoo** [comment]
@Shivanshmundra Please change the name of the model also.

**Comment by Shivanshmundra** [comment]
@gautamjajoo @thatbrguy Is it fine now?
Should I need to add a doc explaining model in naive way and it's versions or let keep it this way?

**Comment by Ram81** [comment]
@Shivanshmundra also can you test whether export works for caffe and keras, it is recommended that export should work for at least the framework in which it is written.

**Comment by Shivanshmundra** [comment]
@Ram81 Export work in caffe part.

**Pull request merged**
