### PR TITLE
Fixed the padding calculation bug

### PR DESCRIPTION
**Pull request by sotanishy**
When the padding is not an integer, like 1/2 or -1/2, it should be rounded up but instead it was rounded down, causing errors.

### CODE REVIEW

**Comment by Ram81** [comment]
@sotanishy GoogleNet export still doesn't work can you look into that.

**Comment by sotanishy** [comment]
Xception didn't work before but after the change it worked.

**Comment by Ram81** [comment]
@sotanishy can you test whether all the models mentioned in README are working fine or is there some model which is breaking.

**Comment by sotanishy** [comment]
I haven't tested everything yet but GoogleNet export for keras worked.

**Comment by Ram81** [comment]
@sotanishy can you fix the Travis CI issues and test all the models listed in tested models (check if any other model which was working earlier is not breaking after the change). Once you are done with that we can go forward with the review.

**Comment by sotanishy** [comment]
Importing keras models such as inception and VQA failed. I'm looking into why but I doubt it's related to the changes I made. Import and export for other models currently available in keras worked. GoogleNet and DenseNet, which were not available in keras before, were successfully exported to keras, too.

**Comment by Ram81** [comment]
@sotanishy the inception models were working fine before the change right?
I encountered a similar issue while fixing the bug can you please verify once again and if needed please fix the issue.

**Comment by sotanishy** [comment]
Exporting and importing them again in caffe worked, but the parameter count was more than what's mentioned in the issue.

**Pull request closed without merging**
