### PR TITLE
Modify model zoo UI #311

### PR DESCRIPTION
**Pull request by MuLx10**
Fixes issue #311 
This PR incorporates a load more button which redirects to the zooSearch page. The zooSearch page displays the models in the card view with a preview of the architecture.

### CODE REVIEW

**Comment by Ram81** [comment]
@MuLx10 I think you can remove package.json from the PR.

**Comment by utsavgarg** [comment]
@MuLx10 If this covers changes done in https://github.com/Cloud-CV/Fabrik/pull/315 can you close that?

**Comment by utsavgarg** [comment]
@MuLx10 This is really nice :) A few suggestions:
image
The text in the zoo isn't centred, there seems to be more whitespace on the right.

Also, by redirecting to a new page, I meant a fully different view, not in a modal, as this seems cluttered. So if we can have a new page, which shows all models arranged in card view by category and have a search bar at the top which filters the models dynamically, that would be great.

**Comment by utsavgarg** [comment]
Also, if this covers the changes made in #321, please close that too.

**Comment by laylalaisy** [comment]
Ok，I will check that tomorrow. Since it’s midnight in China and I am in gym now. Thank you and I’m looking forward to making more contributions to Fabrik. I definitely like this project!

**Pull request closed without merging**
