### PR TITLE
Tested DeepYeast and SpeechNet

### PR DESCRIPTION
**Pull request by adamstafa**

### CODE REVIEW

**Comment by utsavgarg** [comment]
@adamstafa Can you also add a link to visualize the model?

**Comment by adamstafa** [comment]
@utsavgarg I don't know how. Is there any documentation for this?

**Comment by utsavgarg** [comment]
@adamstafa you can import these models in the hosted version at http://fabrik.cloudcv.org and then click on the share button which will give you a link.

**Comment by adamstafa** [comment]
@utsavgarg Done.

**Comment by utsavgarg** [comment]
Thanks :+1:

**Pull request merged**
