### PR TITLE
Fix #198: Fabrik now works on Edge

### LINKED ISSUE #198: Fabrik Doesn't work on Edge
Fabrik doesn't seem to be working on the latest version of edge. Seems to be an issue w/ jsplumb.

As a temporary fix, can I add a message that says please use Google Chrome to access Fabrik?

### PR DESCRIPTION
**Pull request by NSDCars5**
**Issue 1: Dragging/dropping layers did not work:**

This issue was caused due to the spec set for setData/getData in drag-drop events, where the data is stored in a "protected mode", ie. no event other than the original one is allowed to access it. Firefox and Chrome don't follow the W3C spec so setData/getData works there, but Edge follows the spec and doesn't allow it.

More info here: https://stackoverflow.com/questions/11927309/html5-dnd-datatransfer-setdata-or-getdata-not-working-in-every-browser-except-fi

The most effective solution is to just use a different means of storing what is being dragged or dropped, so I used a React state variable.

**Issue 2: Models could not be imported from file:**

This seems to have been caused due to the fact that while every other browser sends a .prototxt file with content-type application/octet-stream, Edge sends it with text/plain. Simply allowing text/plain files to be imported as models works, and invalid files will still be caught by the try/except blocks.

### CODE REVIEW

**Comment by utsavgarg** [comment]
@NSDCars5 We faced some issues with exports, where the `number` text fields are being treated as plain text fields in Edge, and it causes data type issues in the backend. Can you see if there is a way to fix this?

**Comment by NSDCars5** [comment]
@utsavgarg I'll check. Can you point me to an example?

**Comment by utsavgarg** [comment]
@NSDCars5 For example, the data layer in COCO Caption has a batch size argument.

**Comment by NSDCars5** [comment]
@utsavgarg Is this where changing the batch size results in an "Number has type str, but expected one of: int, long"? I can reproduce this even in Chrome, this may not be a bug in Edge in particular. 

I fixed the problem, but since it's not related to Edge, should I make it a separate PR?

**Comment by virajprabhu** [comment]
@NSDCars5 A separate PR would be great! After we merge that, can you pull upstream changes and  we'll try to see if there are still outstanding issues with Windows?

**Comment by NSDCars5** [comment]
@vijayprabhu No problem, will do.

**Comment by utsavgarg** [comment]
LGTM :)

**Pull request merged**
