### PR TITLE
Adding the Mobile Net Model to the Fabrik Model Zoo

### PR DESCRIPTION
**Pull request by jj7302**
Hi this is a pull request adding Mobile Net to the Fabrik Model Zoo for a google code in task.

### CODE REVIEW

**Comment by virajprabhu** [comment]
Thanks @jj7302. Can you add a link to the original repo/project page/paper for this model?

**Comment by utsavgarg** [comment]
@jj7302 Thanks for your submission, a few suggestions:
* The import doesn't work as the JSON contains some activations as `relu6` which are not valid
* Please also add the link to visualize this model in the tested models' list. (Check discussion in #235 for details)

**Comment by virajprabhu** [comment]
@jj7302 Thanks, but there still is an error with loading the model. Have you tried debugging to make sure there are no unsupported layers / attributes in the prototxt?

**Comment by jj7302** [comment]
I do not know how to do that.

**Comment by utsavgarg** [comment]
Closing due to inactivity.

**Pull request closed without merging**
