### PR TITLE
Created a setup instruction for Windows 10

### PR DESCRIPTION
**Pull request by sotanishy**

### CODE REVIEW

**Comment by sotanishy** [comment]
Made a mistake resolving conflicts. Please wait until I fix it.

**Comment by sotanishy** [comment]
I fixed the conflict.

**Comment by Ram81** [comment]
@sotanishy can you try setting up Fabrik on windows independently and not in a linux VM, the goal of this task is to figure out issues while installing on windows.

**Comment by sotanishy** [comment]
@Ram81 Redis and Caffe are not officially supported on Windows which makes the installation really complicated. Using WSL is by far the easiest way to install it on Windows.

**Comment by sotanishy** [comment]
Reopened the PR #414

**Pull request closed without merging**
