### PR TITLE
Fix #115: Added music tagger json model for model zoo

### LINKED ISSUE #115: Add RNN / LSTM examples for Keras in ModelZoo
Keras supports recurrent layers like LSTM / RNN / GRU etc. Right now model zoo for Fabrik doesn't contain any examples of network that uses these layers. 

We should add a few examples to demonstrate the capability of using recurrent layers in a network and to test how import / export works for these layers.

### PR DESCRIPTION
**Pull request by valkyrie-101**
Added [music_tagger_crnn.py](https://github.com/fchollet/deep-learning-models/blob/master/music_tagger_crnn.py) json model in examples. Part of #115 .

### CODE REVIEW

**Comment by utsavgarg** [comment]
@valkyrie-101 please fix merge conflicts

**Comment by utsavgarg** [comment]
@valkyrie-101 you haven't added this model to `topBar.js` and therefore it's not accessible from the frontend. Also, there an error in loading this model, please do not submit models without testing them.

**Comment by virajprabhu** [comment]
@valkyrie-101 Any update on this?

**Comment by virajprabhu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
