### PR TITLE
Fix #285: nondescript 'dim' error removed

### LINKED ISSUE #285: Nondescript 'dim' error when adding certain data layers
- **Steps to reproduce the problem:** add an ImageData, Data, HD5Data, WindowData or MemoryData layer.

- **The expected behaviour:** Layer is added without incident.
- **The observed behaviour:** Error that says 'dim', and nothing else. [Example.](https://i.imgur.com/fcMSAsG.mp4)

This seems to be an issue with the backend, can I work on this?

### PR DESCRIPTION
**Pull request by namansood**
Some data layers don't have a Dim property, and checking for them fails. However, the data(layer) function in ide/utils/shapes.py, which these layers end up running through, has thorough checking for all data layer types, so this just lets that function handle the checks, and raises a suitable exception if a property is missing.

@Ram81 Suggestions/improvements welcome.

### CODE REVIEW

**Comment by NSDCars5** [comment]
Still not sure what to do for HDF5Data.

**Comment by utsavgarg** [comment]
@NSDCars5 Could you check the failing build?

**Comment by utsavgarg** [comment]
@NSDCars5 No worries, take your time.

**Comment by utsavgarg** [comment]
@NSDCars5 Have you been able to work on this?

**Comment by Ram81** [comment]
@utsavgarg Let me handle this one

**Comment by Ram81** [comment]
Fixed in #331.

**Pull request closed without merging**
